# Generated by Django 4.2.3 on 2023-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(blank=True, null=True)),
                ('Email', models.TextField(blank=True, null=True)),
                ('Password', models.TextField(blank=True, null=True)),
                ('User_ID', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
